version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/cicdtest
    overwrite: true

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/cicdtest
    owner: root
    group: root
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
